### ISSUE TITLE
Your article makes reference to a missing repo

### ISSUE THREAD

**Issue by StoneCypher** [greydanus/crypto-rnn#1]
Your article [here](https://greydanus.github.io/2017/01/07/enigma-rnn/) makes reference to a [vignere rnn](https://github.com/greydanus/vigenere-rnn) which appears to not actually exist, just above the headline "Decoding the Enigma."

Perhaps is the repo private?

**Comment by greydanus** [comment]
Hey @StoneCypher, thanks for your interest. I used to have separate repos for the Vigenere, Enigma, and Autokey ciphers. Now they're all subfolders of this repo. Just navigate to the vigenere-rnn folder of this repo. I fixed the link on my blog post.
